apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advanced-python-ingress
spec:
  rules:
    - host: advanced.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: advanced-python-service
                port:
                  number: 80
